version: "3.3"

volumes:
    zabbix-db: {}

services:

  zabbixdb:
    image: monitoringartist/zabbix-db-mariadb:latest
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - zabbix-db:/var/lib/mysql
    environment:
      - MARIADB_USER=zabbix
      - MARIADB_PASS=my_password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  zabbixserver:
    image: monitoringartist/dockbix-xxl:latest
    depends_on:
      - zabbixdb
    ports:
      - "80:80"
      - "10051:10051"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ZS_DBHost=zabbixdb
      - ZS_DBUser=zabbix
      - ZS_DBPassword=my_password
      - XXL_zapix=true
      - XXL_grapher=true
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    #        resources:
    #          limits:
    #            memory: 128M
    #          reservations:
    #            memory: 64M

  zabbixagent:
    image: monitoringartist/dockbix-agent-xxl-limited:latest
    depends_on:
      - zabbixserver
    volumes:
      - /:/rootfs
      - /var/run:/var/run
    environment:
      - ZA_Server=zabbixserver
      - ZA_ServerActive=zabbixserver
    deploy:
      mode: global
      placement:
        constraints:
          - node.hostname!=manager1
