version: '3.1'


#networks:
#  net:
#    driver: host



zabbix-db-storage:
  image: busybox:latest
  volumes:
    - /var/lib/mysql

zabbix-db:
  image: monitoringartist/zabbix-db-mariadb
  volumes:
    - /backups:/backups
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - zabbix-db-storage
  environment:
    - MARIADB_USER=zabbix
    - MARIADB_PASS=my_password

zabbix-server:
  image: monitoringartist/zabbix-2.4:latest
  ports:
    - "80:80"
    - "10051:10051"
  volumes:
    - /etc/localtime:/etc/localtime:ro
  links:
    - zabbix-db:zabbix.db
  environment:
    - ZS_DBHost=zabbix.db
    - ZS_DBUser=zabbix
    - ZS_DBPassword=my_password

services:
#  zabbix-server:
#    image: monitoringartist/zabbix-3.0-xxl:latest
#    environment:
#      - ZS_DBHost=zabbix.db
#      - ZS_DBUser=zabbix
#      - ZS_DBPassword=my_password
#      - XXL_zapix=true
#      - XXL_grapher=true
#      - XXL_apiuser=Admin
#      - XXL_apipass=zabbix
#    links:
#      - zabbix-db:zabbix.db
#    ports:
#      - 8888:80
#    volumes:
#      - dbZabbix:/var/lib/mysql
#    deploy:
#      replicas: 1
  zabbix-agent:
    image: monitoringartist/dockbix-agent-xxl-limited:latest
#    networks:
#      - net
    volumes:
      - /:/rootfs
      - /var/run:/var/run
    links:
      - zabbix-server:zabbix.server
    environment:
      - ZA_Server=zabbix-server
      - ZA_ServerActive=zabbix-server
    deploy:
      mode: global